# Site Configuration
remote_theme: cotes2020/jekyll-theme-chirpy

lang: ko-KR
timezone: Asia/Seoul

title: RoCo Tech Blog
tagline: Romantic Coders의 개발 여정
description: 서비스 개발 회고와 기술 경험을 공유하는 RoCo 팀 블로그

url: "https://romantic-coders.github.io"

github:
  username: Romantic-Coders

social:
  name: RoCo Team
  email: team@roco.dev
  links:
    - https://github.com/Romantic-Coders

author:
  name: RoCo Team
  bio: 낭만적인 코더들의 모임

# Multiple Authors
authors:
  KeunyoungSong:
    name: "송근영"
    bio: "Fullstack Developer"
    avatar: "/assets/img/avatars/KeunyoungSong.jpg"
    links:
      - label: "GitHub"
        icon: "fab fa-github"
        url: "https://github.com/KeunyoungSong"
  
  Dsanj97:
    name: "허동석"
    bio: "Backend Developer"
    avatar: "/assets/img/avatars/Dsanj97.jpg"
    links:
      - label: "GitHub"
        icon: "fab fa-github"
        url: "https://github.com/Dsanj97"
  
  lilble:
    name: "김예림"
    bio: "Backend Developer"
    avatar: "/assets/img/avatars/lilble.jpg"
    links:
      - label: "GitHub"
        icon: "fab fa-github"
        url: "https://github.com/lilble"
  
  kimhayeon00:
    name: "김하연"
    bio: "Frontend Developer"
    avatar: "/assets/img/avatars/kimhayeon00.jpg"
    links:
      - label: "GitHub"
        icon: "fab fa-github"
        url: "https://github.com/kimhayeon00"
  
  j1nzero:
    name: "j1nzero"
    bio: "Designer"
    avatar: "/assets/img/avatars/j1nzero.jpg"
    links:
      - label: "GitHub"
        icon: "fab fa-github"
        url: "https://github.com/j1nzero"

theme_mode: dark
avatar: /assets/img/roco-logo.png
toc: true
paginate: 10
markdown: kramdown

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  syntax_highlighter: rouge

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
