# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: ko-KR

# Change to your timezone
timezone: Asia/Seoul

# jekyll-seo-tag settings
title: RoCo Tech Blog
tagline: Romantic Coders의 개발 여정
description: >-
  서비스 개발 회고와 기술 경험을 공유하는 RoCo 팀 블로그

# Fill in the protocol & hostname for your site
url: "https://romantic-coders.github.io"

github:
  username: Romantic-Coders

social:
  name: RoCo Team
  email: team@roco.dev
  links:
    - https://github.com/Romantic-Coders

# Site Author - Default author
author:
  name: RoCo Team
  bio: 낭만적인 코더들의 모임

# Multiple Authors Configuration
authors:
  KeunyoungSong:
    name: "송근영"
    bio: "Fullstack Developer"
    avatar: "/assets/img/avatars/KeunyoungSong.jpg"
    links:
      - label: "GitHub"
        icon: "fab fa-github"
        url: "https://github.com/KeunyoungSong"
  
  Dsanj97:
    name: "허동석"
    bio: "Backend Developer"
    avatar: "/assets/img/avatars/Dsanj97.jpg"
    links:
      - label: "GitHub"
        icon: "fab fa-github"
        url: "https://github.com/Dsanj97"
  
  lilble:
    name: "김예림"
    bio: "Backend Developer"
    avatar: "/assets/img/avatars/lilble.jpg"
    links:
      - label: "GitHub"
        icon: "fab fa-github"
        url: "https://github.com/lilble"
  
  kimhayeon00:
    name: "김하연"
    bio: "Frontend Developer"
    avatar: "/assets/img/avatars/kimhayeon00.jpg"
    links:
      - label: "GitHub"
        icon: "fab fa-github"
        url: "https://github.com/kimhayeon00"
  
  j1nzero:
    name: "j1nzero"
    bio: "Designer"
    avatar: "/assets/img/avatars/j1nzero.jpg"
    links:
      - label: "GitHub"
        icon: "fab fa-github"
        url: "https://github.com/j1nzero"

# Theme mode: [light|dark]
theme_mode: dark

# The CDN endpoint for images
img_cdn:

# Avatar image
avatar: /assets/img/roco-logo.png

# Boolean type, the global switch for TOC in posts
toc: true

comments:
  active: giscus
  giscus:
    repo: Romantic-Coders/romantic-coders.github.io
    repo_id: # GitHub repo ID
    category: # Discussion category name
    category_id: # Discussion category ID
    mapping: pathname
    input_position: bottom
    lang: ko

# Self-hosted static assets
assets:
  self_host:
    enabled: false

pwa:
  enabled: true

paginate: 10

# Docs: https://jekyllrb.com/docs/configuration/markdown/
markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
